# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sadcod.ui'
#
# Created: Tue Jun 27 12:24:38 2017
#      by: PyQt4 UI code generator 4.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(634, 575)
        Dialog.setSizeGripEnabled(False)
        self.horizontalLayoutWidget = QtGui.QWidget(Dialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 100, 631, 34))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setMargin(5)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(self.horizontalLayoutWidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.ipstart_lineEdit = QtGui.QLineEdit(self.horizontalLayoutWidget)
        self.ipstart_lineEdit.setObjectName(_fromUtf8("ipstart_lineEdit"))
        self.horizontalLayout.addWidget(self.ipstart_lineEdit)
        self.label_2 = QtGui.QLabel(self.horizontalLayoutWidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout.addWidget(self.label_2)
        self.ipstop_lineEdit = QtGui.QLineEdit(self.horizontalLayoutWidget)
        self.ipstop_lineEdit.setObjectName(_fromUtf8("ipstop_lineEdit"))
        self.horizontalLayout.addWidget(self.ipstop_lineEdit)
        self.pushButtonScan = QtGui.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonScan.sizePolicy().hasHeightForWidth())
        self.pushButtonScan.setSizePolicy(sizePolicy)
        self.pushButtonScan.setMinimumSize(QtCore.QSize(225, 0))
        self.pushButtonScan.setCheckable(True)
        self.pushButtonScan.setObjectName(_fromUtf8("pushButtonScan"))
        self.horizontalLayout.addWidget(self.pushButtonScan)
        self.verticalLayoutWidget = QtGui.QWidget(Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 130, 631, 441))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.verticalLayout.setMargin(5)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.creditosLabel = QtGui.QLabel(self.verticalLayoutWidget)
        self.creditosLabel.setObjectName(_fromUtf8("creditosLabel"))
        self.verticalLayout.addWidget(self.creditosLabel)
        self.uiTable = QtGui.QTableWidget(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uiTable.sizePolicy().hasHeightForWidth())
        self.uiTable.setSizePolicy(sizePolicy)
        self.uiTable.setAlternatingRowColors(True)
        self.uiTable.setShowGrid(False)
        self.uiTable.setObjectName(_fromUtf8("uiTable"))
        self.uiTable.setColumnCount(6)
        self.uiTable.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.uiTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.uiTable.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.uiTable.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.uiTable.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.uiTable.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.uiTable.setHorizontalHeaderItem(5, item)
        self.uiTable.horizontalHeader().setVisible(True)
        self.uiTable.horizontalHeader().setDefaultSectionSize(95)
        self.uiTable.horizontalHeader().setHighlightSections(False)
        self.uiTable.horizontalHeader().setSortIndicatorShown(True)
        self.uiTable.horizontalHeader().setStretchLastSection(True)
        self.uiTable.verticalHeader().setVisible(False)
        self.uiTable.verticalHeader().setDefaultSectionSize(15)
        self.uiTable.verticalHeader().setHighlightSections(True)
        self.verticalLayout.addWidget(self.uiTable)
        self.uiTable_2 = QtGui.QTableWidget(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uiTable_2.sizePolicy().hasHeightForWidth())
        self.uiTable_2.setSizePolicy(sizePolicy)
        self.uiTable_2.setAlternatingRowColors(True)
        self.uiTable_2.setShowGrid(False)
        self.uiTable_2.setObjectName(_fromUtf8("uiTable_2"))
        self.uiTable_2.setColumnCount(3)
        self.uiTable_2.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.uiTable_2.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.uiTable_2.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.uiTable_2.setHorizontalHeaderItem(2, item)
        self.uiTable_2.horizontalHeader().setVisible(True)
        self.uiTable_2.horizontalHeader().setDefaultSectionSize(110)
        self.uiTable_2.horizontalHeader().setHighlightSections(False)
        self.uiTable_2.horizontalHeader().setMinimumSectionSize(50)
        self.uiTable_2.horizontalHeader().setSortIndicatorShown(True)
        self.uiTable_2.horizontalHeader().setStretchLastSection(True)
        self.uiTable_2.verticalHeader().setVisible(False)
        self.uiTable_2.verticalHeader().setDefaultSectionSize(15)
        self.uiTable_2.verticalHeader().setHighlightSections(True)
        self.verticalLayout.addWidget(self.uiTable_2)
        self.pushButtonConectar = QtGui.QPushButton(self.verticalLayoutWidget)
        self.pushButtonConectar.setEnabled(False)
        self.pushButtonConectar.setToolTip(_fromUtf8(""))
        self.pushButtonConectar.setStatusTip(_fromUtf8(""))
        self.pushButtonConectar.setCheckable(True)
        self.pushButtonConectar.setObjectName(_fromUtf8("pushButtonConectar"))
        self.verticalLayout.addWidget(self.pushButtonConectar)
        self.pushButtonDestroy = QtGui.QPushButton(self.verticalLayoutWidget)
        self.pushButtonDestroy.setEnabled(False)
        self.pushButtonDestroy.setCheckable(True)
        self.pushButtonDestroy.setObjectName(_fromUtf8("pushButtonDestroy"))
        self.verticalLayout.addWidget(self.pushButtonDestroy)
        self.estadoLabel = QtGui.QLabel(self.verticalLayoutWidget)
        self.estadoLabel.setText(_fromUtf8(""))
        self.estadoLabel.setObjectName(_fromUtf8("estadoLabel"))
        self.verticalLayout.addWidget(self.estadoLabel)
        self.gridLayoutWidget = QtGui.QWidget(Dialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 10, 631, 101))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setMargin(5)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_7 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 1, 3, 1, 1)
        self.label_3 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1)
        self.label_8 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout.addWidget(self.label_8, 2, 3, 1, 1)
        self.srvport_spinBox = QtGui.QSpinBox(self.gridLayoutWidget)
        self.srvport_spinBox.setMinimum(1)
        self.srvport_spinBox.setMaximum(65535)
        self.srvport_spinBox.setProperty("value", 27016)
        self.srvport_spinBox.setObjectName(_fromUtf8("srvport_spinBox"))
        self.gridLayout.addWidget(self.srvport_spinBox, 1, 1, 1, 1)
        self.ctrport_spinBox = QtGui.QSpinBox(self.gridLayoutWidget)
        self.ctrport_spinBox.setMinimum(1)
        self.ctrport_spinBox.setMaximum(65535)
        self.ctrport_spinBox.setProperty("value", 27017)
        self.ctrport_spinBox.setObjectName(_fromUtf8("ctrport_spinBox"))
        self.gridLayout.addWidget(self.ctrport_spinBox, 0, 1, 1, 1)
        self.extrainfo_checkBox = QtGui.QCheckBox(self.gridLayoutWidget)
        self.extrainfo_checkBox.setText(_fromUtf8(""))
        self.extrainfo_checkBox.setChecked(True)
        self.extrainfo_checkBox.setObjectName(_fromUtf8("extrainfo_checkBox"))
        self.gridLayout.addWidget(self.extrainfo_checkBox, 1, 4, 1, 1)
        self.delay_doubleSpinBox = QtGui.QDoubleSpinBox(self.gridLayoutWidget)
        self.delay_doubleSpinBox.setSpecialValueText(_fromUtf8("s"))
        self.delay_doubleSpinBox.setDecimals(5)
        self.delay_doubleSpinBox.setMinimum(1e-05)
        self.delay_doubleSpinBox.setMaximum(1.5)
        self.delay_doubleSpinBox.setSingleStep(0.0001)
        self.delay_doubleSpinBox.setProperty("value", 0.0001)
        self.delay_doubleSpinBox.setObjectName(_fromUtf8("delay_doubleSpinBox"))
        self.gridLayout.addWidget(self.delay_doubleSpinBox, 2, 4, 1, 1)
        self.pushButtonReset = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButtonReset.setObjectName(_fromUtf8("pushButtonReset"))
        self.gridLayout.addWidget(self.pushButtonReset, 0, 2, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 2, 1, 1)
        self.label_5 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 0, 3, 1, 1)
        self.label_6 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 2, 0, 1, 1)
        self.seekport_spinBox = QtGui.QSpinBox(self.gridLayoutWidget)
        self.seekport_spinBox.setMinimum(1024)
        self.seekport_spinBox.setMaximum(65535)
        self.seekport_spinBox.setProperty("value", 27000)
        self.seekport_spinBox.setObjectName(_fromUtf8("seekport_spinBox"))
        self.gridLayout.addWidget(self.seekport_spinBox, 2, 1, 1, 1)
        self.timeout_spinBox = QtGui.QSpinBox(self.gridLayoutWidget)
        self.timeout_spinBox.setMinimum(1)
        self.timeout_spinBox.setMaximum(30)
        self.timeout_spinBox.setProperty("value", 5)
        self.timeout_spinBox.setObjectName(_fromUtf8("timeout_spinBox"))
        self.gridLayout.addWidget(self.timeout_spinBox, 0, 4, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Seek and Destroy Call of Duty", None))
        self.label.setText(_translate("Dialog", "desde", None))
        self.ipstart_lineEdit.setText(_translate("Dialog", "10.8.1.1", None))
        self.label_2.setText(_translate("Dialog", "hasta", None))
        self.ipstop_lineEdit.setText(_translate("Dialog", "10.8.128.253", None))
        self.pushButtonScan.setText(_translate("Dialog", "Buscar servidores de Call of Duty", None))
        self.creditosLabel.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600; color:#0000c0;\">SaDCoD v4.5 </span><span style=\" font-weight:600; color:#ff0000;\">(Beta)</span><span style=\" font-weight:600; color:#0000c0;\"> by NiNja Larry</span></p><p align=\"center\"><span style=\" font-family:\'DejaVu Sans Mono\'; font-weight:600; color:#008000;\">Agradecimientos a EliT3, Kuko, UrKO y SAITAMA(D@DI)</span></p></body></html>", None))
        self.uiTable.setSortingEnabled(True)
        item = self.uiTable.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Dirección", None))
        item = self.uiTable.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Versión", None))
        item = self.uiTable.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Jugadores", None))
        item = self.uiTable.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "Mapa", None))
        item = self.uiTable.horizontalHeaderItem(4)
        item.setText(_translate("Dialog", "Modo", None))
        item = self.uiTable.horizontalHeaderItem(5)
        item.setText(_translate("Dialog", "Servidor", None))
        self.uiTable_2.setSortingEnabled(True)
        item = self.uiTable_2.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Jugador", None))
        item = self.uiTable_2.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Puntos", None))
        item = self.uiTable_2.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Latencia", None))
        self.pushButtonConectar.setText(_translate("Dialog", "Seleccione servidor", None))
        self.pushButtonDestroy.setText(_translate("Dialog", "Seleccione servidor", None))
        self.label_7.setText(_translate("Dialog", "pedir  datos extra\n"
"al servidor", None))
        self.label_3.setText(_translate("Dialog", "puerto de control", None))
        self.label_4.setText(_translate("Dialog", "puerto de juego", None))
        self.label_8.setText(_translate("Dialog", "retardo entre envio", None))
        self.pushButtonReset.setText(_translate("Dialog", "Restaurar valores", None))
        self.label_5.setText(_translate("Dialog", "tiempo de espera para\n"
"refrescar datos extra", None))
        self.label_6.setText(_translate("Dialog", "puerto sadcod", None))

